# Generated by Django 5.2.1 on 2025-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='details',
            field=models.TextField(blank=True, verbose_name='Подробности от флориста'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='budget',
            field=models.CharField(choices=[('до 1000', 'до 1000'), ('1000-5000', '1000-5000'), ('от 5000', 'от 5000'), ('не имеет значения', 'Не имеет значения')], default='1000-5000', max_length=50, verbose_name='Бюджет'),
        ),
    ]
