# Generated by Django 5.2.1 on 2025-09-25 08:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_bouquet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='details',
        ),
        migrations.AddField(
            model_name='consultation',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
