# Generated by Django 5.2.6 on 2025-09-25 13:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consultation_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя флориста')),
                ('florist_id', models.IntegerField(unique=True, verbose_name='ID флориста')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Флорист',
                'verbose_name_plural': 'Флористы',
            },
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='consultation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='details',
            field=models.TextField(blank=True, verbose_name='Подробности от флориста'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='budget',
            field=models.CharField(choices=[('up_to_1000', 'До 1000 рублей'), ('1000_5000', '1000-5000 рублей'), ('from_5000', 'От 5000'), ('any', 'Не имеет значения')], default='1000-5000', max_length=50, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='occasion',
            field=models.CharField(choices=[('wedding', 'Свадьба'), ('birthday', 'День рождения'), ('no_occasion', 'Без повода'), ('other', 'Другой повод')], default='Без повода', max_length=50, verbose_name='Повод'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='florist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.florist', verbose_name='Флорист'),
        ),
    ]
