# Generated by Django 5.2.1 on 2025-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_florist_remove_consultation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='courier',
            name='number_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AddField(
            model_name='courier',
            name='tg_chat_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Чат ID курьера в ТГ'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_counted',
            field=models.BooleanField(default=False, verbose_name='Заказ учтен в статистике'),
        ),
    ]
